import importlib.util
src = open("sim_full_top.py").read()
cut = src.split('boot_rom = load_hex("boot_rom.hex")')[0]
ns = {}
exec(cut, ns)
Top = ns['Top']

def load_hex(path):
    return [int(l.strip(), 16) for l in open(path) if l.strip()]

def itype(op, rd, rs1, imm6):
    OP = dict(NOP=0,ADD=1,ADDI=2,SUB=3,AND=4,OR=5,XOR=6,SLL=7,SRL=8,HALT=0xF)
    imm6 &= 0x3F
    return (OP[op] << 12) | (rd << 9) | (rs1 << 6) | imm6

boot_rom = load_hex("boot_rom.hex")  # generated by `python3 build_boot_rom.py`

print("=== TEST 2c: boundary continuity, with a counter zeroed at flash offset 0 first ===")
words  = [itype('ADDI', 6, 0, 0)]              # flash offset 0-1: r6 = 0 (clean baseline,
                                                 # not contaminated by boot_rom's own r6 use)
words += [itype('ADDI', 6, 6, 1)]              # flash offset 2-3: r6 += 1 (should fire
                                                 # EXACTLY ONCE if rebasing is continuous)
words += [itype('NOP', 0, 0, 0)] * 62           # pad: 2 words so far + 62 = 64 words = 128B
                                                  # -> next instruction lands exactly at
                                                  # flash offset 0x80
words += [itype('ADDI', 5, 0, 17)]              # flash offset 0x80-0x81: marker, reached
                                                  # only via correct continuation
words += [itype('HALT', 0, 0, 0)]

flash_bytes = {}
for i, w in enumerate(words):
    flash_bytes[i*2] = (w>>8)&0xFF
    flash_bytes[i*2+1] = w&0xFF

top = Top(boot_rom, flash_bytes)
top.gpio_in_bits = [0x00]*60
steps = 0
while steps < 2000 and not top.halted:
    if not top.step(): break
    steps += 1

print(f"  steps: {steps}  flash_mode: {top.flash_mode}  halted: {top.halted}  final pc: 0x{top.pc:04x}")
print(f"  r5 (marker at flash offset 0x80) = {top.regs[5]}  (expect 17)")
print(f"  r6 (counter, zeroed then incremented once at flash offset 0-3) = {top.regs[6]}  (expect 1)")

if top.regs[5] == 17 and top.regs[6] == 1:
    print("  PASS - flash_addr is genuinely continuous across the 0x0100 boundary")
elif top.regs[6] >= 2:
    print("  FAIL - confirmed wrap: flash offset 0's code re-executed when pc crossed 0x0100")
else:
    print("  UNEXPECTED result - needs closer inspection")
